const DATA_URL='https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/items.json';
const IMG_BASE='https://mcasset.cloud/1.21.11/assets/minecraft/textures/';
let items=[], cart=JSON.parse(localStorage.getItem('mc-cart')||'[]'), category='all', query='';
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function imgFor(name, kind='item'){return `${IMG_BASE}${kind}/${name}.png`}
function imgHtml(name, alt, cls=''){const item=imgFor(name,'item'), block=imgFor(name,'block');return `<img class="${cls}" loading="lazy" src="${item}" alt="${esc(alt)}" data-fallback="${block}" onerror="if(this.dataset.fallback){this.src=this.dataset.fallback;this.dataset.fallback=''}else{this.style.opacity='.12'}"/>`}
function save(){localStorage.setItem('mc-cart',JSON.stringify(cart));renderCart()}
function filtered(){let x=items.filter(i=>i.name!=='air');if(query)x=x.filter(i=>(i.displayName+' '+i.name).toLowerCase().includes(query.toLowerCase()));if(category!=='all')x=x.filter(i=>guessCat(i).includes(category));return x}
function guessCat(i){let n=i.name; if(/sword|bow|crossbow|trident|shield|helmet|chestplate|leggings|boots|mace|spear|armor/.test(n))return 'combat';if(/pickaxe|axe|shovel|hoe|shears|fishing_rod|flint_and_steel|brush|bucket|compass|clock/.test(n))return 'tools';if(/bread|apple|carrot|potato|beef|porkchop|chicken|mutton|rabbit|stew|cookie|cake|melon|berry|fish|honey_bottle|golden_apple/.test(n))return 'food';if(/redstone|piston|lever|button|repeater|comparator|observer|hopper|dispenser|dropper|rail|target|note_block|daylight/.test(n))return 'redstone';if(/ore|ingot|nugget|gem|diamond|emerald|coal|quartz|amethyst|raw_|stick|string|leather|paper|book|dye|shard|shell|bone/.test(n))return 'materials';return 'block'}
function render(){const data=filtered().sort((a,b)=>$('#sort').value==='id'?a.id-b.id:a.displayName.localeCompare(b.displayName));$('#count').textContent=`Найдено: ${data.length}`;$('#grid').innerHTML=data.map(i=>`<article class="card"><div class="pic">${imgHtml(i.name,i.displayName)}</div><div class="name">${esc(i.displayName)}</div><div class="meta">ID ${i.id} · стак ${i.stackSize}</div><button class="add" data-id="${i.id}">В корзину</button></article>`).join('')||'<div class="empty">Ничего не найдено</div>'}
function add(id){const i=items.find(x=>x.id===id);if(!i)return;const row=cart.find(x=>x.id===id);row?row.quantity++:cart.push({id:i.id,name:i.displayName,quantity:1});save()}
function renderCart(){const total=cart.reduce((s,x)=>s+x.quantity,0);$('#cartCount').textContent=total;$('#cartItems').innerHTML=cart.length?cart.map((x,n)=>`<div class="cartRow">${imgHtml(items.find(i=>i.id===x.id)?.name||'barrier',x.name)}<div><b>${esc(x.name)}</b><div class="qty"><button data-dec="${n}">−</button><span>${x.quantity}</span><button data-inc="${n}">+</button></div></div><button class="remove" data-remove="${n}">×</button></div>`).join(''):'<div class="empty">Корзина пока пуста</div>'}
function openCart(){ $('#drawer').classList.add('open');$('#overlay').classList.add('show') }function closeCart(){ $('#drawer').classList.remove('open');$('#overlay').classList.remove('show') }
$('#grid').addEventListener('click',e=>{const b=e.target.closest('.add');if(b)add(Number(b.dataset.id))});$('#search').addEventListener('input',e=>{query=e.target.value;render()});$('#clear').onclick=()=>{$('#search').value='';query='';render()};$('#sort').onchange=render;document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.cat;render()});$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=closeCart;
$('#cartItems').addEventListener('click',e=>{let n;if((n=e.target.dataset.inc)!=null)cart[n].quantity++;if((n=e.target.dataset.dec)!=null){cart[n].quantity--;if(cart[n].quantity<=0)cart.splice(n,1)}if((n=e.target.dataset.remove)!=null)cart.splice(n,1);save()});
$('#orderBtn').onclick=async()=>{if(!cart.length)return alert('Корзина пуста');const nickname=$('#nickname').value.trim(),contact=$('#contact').value.trim();if(!nickname||!contact)return alert('Заполните никнейм и контакт');const btn=$('#orderBtn');btn.disabled=true;try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({customer:{nickname,contact},items:cart})});const type=r.headers.get('content-type')||'';const d=type.includes('application/json')?await r.json():{error:'Сервер вернул HTML вместо API. Проверьте деплой Vercel и наличие папки api/.'};if(!r.ok)throw Error(d.error||'Ошибка');$('#orderNumber').textContent=d.number;$('#success').classList.add('show');cart=[];save();$('#nickname').value='';$('#contact').value='';closeCart()}catch(e){alert(e.message)}finally{btn.disabled=false}};$('#done').onclick=()=>$('#success').classList.remove('show');
fetch(DATA_URL).then(r=>r.json()).then(d=>{items=d;render();renderCart()}).catch(()=>$('#count').textContent='Не удалось загрузить каталог');
